### ISSUE TITLE
Allow configuring the behavior of the release tool using a YAML file

### ISSUE THREAD

**Issue by nicwortel** [leviy/release-tool#4]
At the very least, this should allow users to configure the "release steps" that should be executed when releasing a new version.

The release tool should look for a file in the current working directory (something like `.release-tool.yml`) and read the contents to apply the configuration.

Example `.release-tool.yml`, with default values:

```
versioning-scheme: semantic

vcs:
  git:
    tag-prefix: v
    remote: origin

post-release-actions:
  github-release: ~
```

The configured values should be used when compiling the service container.

See https://github.com/Behat/Behat, https://github.com/sensiolabs-de/deptrac for examples.

- [ ] design a good and scalable configuration format
- [ ] use [symfony/yaml](https://github.com/symfony/yaml) to read the file

Probably requires #7

**Comment by nicwortel** [comment]
Example `.release-tool.yaml`, with default values:

```
versioning-scheme: semantic

vcs:
  git:
    tag-prefix: v
    remote: origin

post-release-actions:
  github-release: ~
```
